export type SettingSectionId =
  | 'general'
  | 'milestones'
  | 'members'
  | 'approval'
  | 'portal'
  | 'agency'
  | 'github'
  | 'slack'
  | 'video-conference'
  | 'api'
  | 'export'
  | 'danger'

export type ConnectionStatus = 'connected' | 'disconnected' | 'warning' | 'none'
